### ISSUE TITLE
typo error 

### ISSUE THREAD

**Issue by Oveys96** [spatialaudio/sciopy#18]
in "setup_m.py" there is a function named "SystemMessageCallback". 
In this message "0x91": "Data holdup: Measurement data could not be sent via the master interface" , 0x92 should be replaced with 0x91.

**Comment by JacobTh98** [comment]
So you mean that the `msg_dict` entry 
`"0x91": "Data holdup: Measurement data could not be sent via the master interface",`
should be changed to:
`"0x92": "Data holdup: Measurement data could not be sent via the master interface",`

**Comment by Oveys96** [comment]
exactly!

**Comment by JacobTh98** [comment]
Done.
